<?
/*
$filename = "imgTest/1.jpg";
$img_names_file_resize = "imgTest/cache/1.jpg";
$nwidth = "200";
$nheight = "200";
$quality = "100";



$captchaIsValid = Mage::helper('forpix')->imgresize($filename, $img_names_file_resize, $nwidth, $nheight);
if ($captchaIsValid) {
    echo '<img src="' . Mage::getBaseUrl() . $img_names_file_resize . '" alt="" />';
} else {
    echo 'Хреново';
}
*/
?>


<?php
$row = $this->getSortImg();

foreach ($row['result'] as $quote):

    $img_names_file_resize =  $quote['name'] . "<br />";
    ?>
    <? echo $img_names_file_resize; ?>
<?php endforeach ?>



<pre>
    <?php // print_r($this->getSortImg());   ?>
</pre>

